version: '3'

services:
  streamer-binance:
    build:
      context: ./streamers
      dockerfile: Dockerfile
    links:
      - rabbitmq
    restart: on-failure
    container_name: eq-trader-streamer-binance
    environment:
      - MARKET_ID=BTCETH
      - NODE_ENV=production
      - EXCHANGE=binance
      - WEBSOCKET=true
      - RABBIT_MQ_ADDR=rabbitmq:5672

  streamer-kraken:
    build:
      context: ./streamers
      dockerfile: Dockerfile
    links:
      - rabbitmq
    restart: on-failure
    container_name: eq-trader-streamer-kraken
    environment:
      - MARKET_ID=BTC/ETH
      - NODE_ENV=production
      - EXCHANGE=kraken
      - WEBSOCKET=false
      - RABBIT_MQ_ADDR=rabbitmq:5672

  rabbitmq:
    image: rabbitmq:alpine
    hostname: rabbitmq
    container_name: eq-trader-rabbitmq
    ports:
      - "5672:5672"

  redis:
    image: redis:alpine
    hostname: redis
    container_name: eq-trader-redis
    ports:
      - "6379:6379"
