version: "2"

services:
  streamer-binance:
    build:
      context: ./streamers
      dockerfile: Dockerfile
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    environment:
      - EXCHANGE=binance
      - RABBIT_MQ_ADDR=rabbitmq:5672

  streamer-bitmex:
    build:
      context: ./streamers
      dockerfile: Dockerfile
    links:
      - rabbitmq
    depends_on:
      - rabbitmq
    environment:
      - EXCHANGE=bitmex
      - RABBIT_MQ_ADDR=rabbitmq:5672

  rabbitmq:
    image: rabbitmq:alpine
    hostname: rabbitmq
    container_name: rabbitmq
    ports:
      - "5672:5672"

  redis:
    image: redis:alpine
    hostname: redis
    container_name: redis
    ports:
      - "6379:6379"
